apiVersion: v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: default
spec:
  containers:
    - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      name: nginx
      ports:
        - containerPort: {{ .Values.appPort }}
          protocol: TCP
      imagePullPolicy: IfNotPresent
      resources:
        {{- toYaml .Values.resources | nindent 12 }}

