apiVersion: v1
kind: Service
metadata:
  name: nodeport
  namespace: default
spec:
  ports:
    - name: http
      port: {{ .Values.appPort }}
      protocol: TCP
      nodePort: 32180
  selector:
    app: frontend
  type: NodePort
